org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=2
kotlin.daemon.jvmargs=-Xmx3g
android.useAndroidX=true
android.nonTransitiveRResources=true
kotlin.code.style=official
# KSP incremental workaround for IllegalStateException: unexpected jvm signature
ksp.incremental=false
ksp.incremental.log=false
